### ISSUE TITLE
Building a Bookworm

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/lab-workshops#12]
We're running a live instance here: http://bookworm.library.yale.edu/collections/vogue/

The latest code, more up-to-date code is here: 

API: https://github.com/bookworm-project/bookwormDB
Default FrontEnd (HighCharts line graph): https://github.com/Bookworm-project/BookwormGUI

In addition, Ben has been working on d3-based visualizations from the same API backend, here: https://github.com/bmschmidt/BookwormD3

We would have texts ready to go for attendees. Ideas for texts to prepare:

* Vogue photo captions [PL]
* Medical Heritage Library pre-1923 texts [MG]

**Comment by duhaime** [comment]
Thanks @pleonard212! I'm looking forward to this one...
