### ISSUE TITLE
Bookworm :: CGI Connection Error?

### ISSUE THREAD

**Issue by triplingual** [YaleDHLab/lab-workshops#19]
I'm able to get Federalist mostly working, except. Except that I get the spinning loading wheel of death. In my apache error log, there's a mostly helpful error:

`[Tue Aug 23 20:50:42.716682 2016] [cgi:error] [pid 12821] [client 130.132.173.70:43443] AH01215: ERROR:root:/etc/mysql/my.cnf, referer: http://54.152.238.88/federalist/`

Don't try to access the instance right now, as it's shut down. Do I need my bookworm db credentials in `/etc/mysql/my.cnf`? I don't really care why it's looking there instead of `~/.my.cnf` as long as I can make the connection, though it's a little odd.

**Comment by duhaime** [comment]
Sorry @triplingual, I missed a character when typing the cgi bit (it's now fixed). When moving the flask server, the command should have been: `sudo cp ~/BookwormDB/bookwormDB/bin/dbbindings.py /usr/lib/cgi-bin/`. It was confusingly `sudo cp ~/BookwormDB/bookwormDB/bin/dbbindings.py /usr/lib/cgi-bin` before, so you may want to cat `/usr/lib/cgi-bin` to see if it's indeed a Python file! If it's a directory, can you check that dbbindings.py is in that directory?

**Comment by triplingual** [comment]
```
ubuntu@ip-172-31-14-46:~$ ls -la /usr/lib/cgi-bin/
total 12
drwxr-xr-x  2 root root 4096 Aug 23 20:51 .
drwxr-xr-x 66 root root 4096 Aug 23 18:28 ..
-rwxrwxr-x  1 root root 2167 Aug 23 20:51 dbbindings.py
```

Definitely a file in a directory.

**Comment by duhaime** [comment]
Just to check, what happens if you run the following?

```
sudo a2enmod cgi
sudo service apache2 restart
```

**Comment by triplingual** [comment]
```
ubuntu@ip-172-31-14-46:~$ sudo a2enmod cgi
Module cgi already enabled
```

Starting the webserver succeeds, but same issue, same error. I believe I've got my EC2 rules configured correctly. Inbound:
![screenshot 2016-08-24 08 03 27](https://cloud.githubusercontent.com/assets/1789625/17929871/5d37b312-69d1-11e6-97ad-f84348454a10.png)

Outbound is all/all/all/0.0.0.0/0

There's no alias from cgi-bin to /usr/lib/cgi-bin, FWIW. That doesn't look like the issue to me, but I'm shallow on this, remember.

**Comment by triplingual** [comment]
Never mind on the alias. Just learned about and found `/conf-enabled/serve-cgi-bin.conf`.

**Comment by duhaime** [comment]
Hmm, if you're following the tutorial you shouldn't need to configure `/etc/apache2/conf-enabled/serve-cgi-bin.conf` (you also would only need two security groups--one for HTTP on port 80 and the other for SSH on port 22); were you wanting to do something different than the tutorial? If so, does [this thread](http://askubuntu.com/questions/547391/apache2-4-7-on-ubuntu-14-04-wont-execute-python-cgi-file-the-site-displays-pyt) help you?

**Comment by triplingual** [comment]
Turns out I may have built from inside an earlier directory, which would explain the fact that my GUI indicated it was for The Simpsons rather than the Federalist Papers.

Seems to be a success! http://54.152.238.88/federalist/

Now where's that how-to on making my own corpus? ;-)

**Comment by duhaime** [comment]
Haha, excellent! Peter and I started talking about expanding the guide to cover building on a CentOS/Amazon-flavored instance, and about also covering building a bookworm on a flat text file collection. Right now we're full steam ahead on end of summer projects (including the DH-Rees site, which is moving quickly)!

Is it safe to close this issue?

**Comment by triplingual** [comment]
Def. In fact . . .
