### ISSUE TITLE
Bookworm on Ubuntu - consider @locahost for MySQL permissions

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/lab-workshops#21]
Several bookworm scripts (specifically, those for flushing and reloading data) assume `'dbadmin'@'localhost'` rather than `'dbadmin'@'127.0.0.1'`.  Not sure how interchangeable they are; we could either add in localhost as an addition or swap it out.

**Comment by duhaime** [comment]
Sure thing! #22 should take car of this...
