### ISSUE TITLE
word-vectors workshop: To be done

### ISSUE THREAD

**Issue by JoshuaDull** [YaleDHLab/lab-workshops#86]
What's left to do on the word-vectors workshop:
- [x] fix PDF links
- [x] Add Hierarchical explanation 
- [x] explain centroid more?
- [x] Review for typos/mistakes
- [x] Add resources section/links to more info

**Comment by JoshuaDull** [comment]
@duhaime This is more so I can remember what's left for me to do. Feel free to add more if it helps you!

**Comment by pleonard212** [comment]
Do we need to include any reference to the 2018 Mimno/Antoniak paper on stability, especially on small corpora, and to the (development branch only) support for word vectors in Mallet, which specifically include randomized bootstrap sampling which helps with this?

https://mimno.infosci.cornell.edu/info3350/readings/antoniak.pdf
https://github.com/mimno/Mallet/wiki/Word-Embeddings

Disregard if we are already mentioning or if not appropriate!

**Comment by duhaime** [comment]
We should totally add a link to the Mimno/Antoniak study. It provides a nice overview of the origins of randomness in embedding models and gives a nuanced response to the common question "how much data do I need to train an embedding model?" Good find!
